// Fonts
import { fontSans, fontMono } from "./fonts"
// Components
import { Footer, Header } from "@/components"
// Global Css
import "./globals.css"
// 
import { cn } from "@/lib/utils"
// Meta Data
// Meta Data
export const metadata = {
  title: "Book Publishing Company",
  description: "Generated by Book Publishing Company",
  robots: {
    index: false,
    follow: false,
    nocache: true,
    googleBot: {
      index: false,
      follow: false,
      noimageindex: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth snap-mandatory">
      <body className={cn("font-sans font-normal scroll-smooth text-card-foreground", fontSans.variable, fontMono.variable)}>
        <Header />
        <main>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}